# Generated by Django 3.2.17 on 2023-05-30 06:43

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=50)),
                ('reputation_point', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=200)),
                ('date_of_post', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('desire', models.TextField(default='', max_length=255)),
                ('expiration', models.DateTimeField(default=datetime.datetime(2023, 6, 6, 6, 43, 56, 578204, tzinfo=utc))),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('visibile', models.BooleanField(default=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_detail', models.CharField(default='', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_emailVerified', models.BooleanField(default=False)),
                ('is_phoneVerified', models.BooleanField(default=False)),
                ('reputation_rating', models.DecimalField(decimal_places=0, default=0, max_digits=1000)),
                ('total_review', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=100)),
                ('reason', models.TextField(default='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance', models.BooleanField(default=False)),
                ('date_offered', models.DateTimeField(auto_now_add=True)),
                ('post_confirmation', models.BooleanField(default=False)),
                ('offer_confirmation', models.BooleanField(default=False)),
                ('visibile', models.BooleanField(default=True)),
                ('offered_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_model', to='api.item')),
            ],
        ),
    ]
