# Generated by Django 4.1.4 on 2022-12-24 02:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=200)),
                ('date_of_post', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('desire', models.CharField(default='', max_length=200)),
                ('offer_period', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=0, max_length=1)),
                ('is_tradable', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
    ]
