# Generated by Django 4.1.4 on 2023-01-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_image_image_alter_image_item_id_and_more'),
        ('api', '0010_alter_user_id'),
    ]

    operations = [
    ]
