# Generated by Django 4.1.4 on 2023-01-20 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_offer_post_date_posted_delete_offers_offer_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 10, 52, 21, 999365, tzinfo=datetime.timezone.utc)),
        ),
    ]
