# Generated by Django 4.1.5 on 2023-01-20 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_post_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 13, 40, 5, 529295, tzinfo=datetime.timezone.utc)),
        ),
    ]
