
# Generated by Django 4.1.4 on 2023-01-20 20:35


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_post_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',

            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 20, 35, 46, 204008, tzinfo=datetime.timezone.utc)),
        )
    ]
