# Generated by Django 4.1.4 on 2023-01-21 02:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_post_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 2, 4, 25, 66884, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_traded', models.DateTimeField(auto_now_add=True)),
                ('item_traded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('newUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newUser', to='api.user')),
                ('oldUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldUser', to='api.user')),
            ],
        ),
    ]
