# Generated by Django 4.1.5 on 2023-01-21 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_post_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 2, 0, 16, 855666, tzinfo=datetime.timezone.utc)),
        ),
    ]
