# Generated by Django 4.1.5 on 2023-01-24 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_post_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 12, 3, 58, 274708, tzinfo=datetime.timezone.utc)),
        ),
    ]
