# Generated by Django 4.1.4 on 2023-01-23 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_tradehistory_item_traded_tradehistory_newitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 12, 41, 3, 546345, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='TradeHistory',
        ),
    ]
