# Generated by Django 4.1.4 on 2023-01-23 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_post_expiration_delete_tradehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='desire',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_tradable',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer_period',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_detail',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 13, 0, 2, 80444, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
