# Generated by Django 4.1.4 on 2023-01-23 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_item_desire_remove_item_is_tradable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 13, 5, 3, 60197, tzinfo=datetime.timezone.utc)),
        ),
    ]
