# Generated by Django 4.1.4 on 2023-01-23 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_post_expiration_alter_user_phone_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='desire',
        ),
        migrations.AddField(
            model_name='item',
            name='desire',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 13, 43, 3, 927203, tzinfo=datetime.timezone.utc)),
        ),
    ]
