# Generated by Django 4.1.4 on 2023-01-24 14:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_item_category_alter_post_expiration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='desire',
        ),
        migrations.AddField(
            model_name='post',
            name='desire',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 14, 7, 18, 10698, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_detail',
            field=models.CharField(default='', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
