# Generated by Django 4.1.4 on 2023-01-25 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_item_desire_post_desire_alter_post_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_emailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phoneVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 5, 27, 55, 921836, tzinfo=datetime.timezone.utc)),
        ),
    ]
