# Generated by Django 4.1.4 on 2023-01-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_post_expiration'),
        ('api', '0029_alter_post_expiration_alter_user_email'),
    ]

    operations = [
    ]
