# Generated by Django 4.1.5 on 2023-01-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_post_expiration'),
        ('api', '0029_alter_post_expiration_alter_user_email'),
    ]

    operations = [
    ]
