# Generated by Django 4.1.4 on 2023-01-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_post_expiration'),
        ('api', '0030_merge_20230125_2045'),
    ]

    operations = [
    ]
