# Generated by Django 4.1.4 on 2023-01-26 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_categories_alter_post_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 12, 53, 14, 901888, tzinfo=datetime.timezone.utc)),
        ),
    ]
