# Generated by Django 4.1.4 on 2023-01-28 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20230125_2102'),
        ('api', '0031_merge_20230126_2153'),
        ('api', '0035_alter_post_expiration'),
    ]

    operations = [
    ]
