# Generated by Django 4.1.5 on 2023-01-28 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_merge_20230128_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 2, 58, 14, 440449, tzinfo=datetime.timezone.utc)),
        ),
    ]
