# Generated by Django 4.1.4 on 2023-01-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20230126_1950'),
        ('api', '0037_alter_post_expiration'),
    ]

    operations = [
    ]
