# Generated by Django 4.1.5 on 2023-01-31 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_20230128_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 10, 16, 36, 826967, tzinfo=datetime.timezone.utc)),
        ),
    ]
