# Generated by Django 4.1.4 on 2023-02-04 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_offer_first_confirmation_offer_second_confirmation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='first_confirmation',
            new_name='offer_confirmation',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='second_confirmation',
            new_name='post_confirmation',
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 4, 7, 54, 719271, tzinfo=datetime.timezone.utc)),
        ),
    ]
