# Generated by Django 3.2.17 on 2023-02-06 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_first_confirmation_offer_offer_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 11, 47, 23, 629207, tzinfo=utc)),
        ),
    ]
