# Generated by Django 4.1.4 on 2023-02-06 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_post_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_review',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 12, 45, 16, 379691, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='reputation_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
