# Generated by Django 4.1.4 on 2023-02-06 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_user_total_review_alter_post_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 12, 50, 50, 949978, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='reputation_rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000),
        ),
    ]
