# Generated by Django 3.2.17 on 2023-02-06 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_post_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 14, 37, 46, 55570, tzinfo=utc)),
        ),
    ]
