# Generated by Django 3.2.17 on 2023-02-06 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_post_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 15, 40, 19, 969613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postcategories',
            name='Categories_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
