# Generated by Django 3.2.17 on 2023-02-06 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20230207_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategories',
            old_name='Categories_id',
            new_name='Catagory_categories_id',
        ),
        migrations.RenameField(
            model_name='postcategories',
            old_name='post_id',
            new_name='Catagory_post_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 15, 47, 12, 112571, tzinfo=utc)),
        ),
    ]
