# Generated by Django 3.2.17 on 2023-02-06 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20230207_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 15, 50, 57, 266468, tzinfo=utc)),
        ),
    ]
