# Generated by Django 3.2.17 on 2023-02-06 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20230207_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategories',
            name='catagories_categories_id',
        ),
        migrations.RemoveField(
            model_name='postcategories',
            name='catagories_post_id',
        ),
        migrations.AddField(
            model_name='postcategories',
            name='catagories_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcategories',
            name='post_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 16, 25, 28, 655949, tzinfo=utc)),
        ),
    ]
