# Generated by Django 3.2.17 on 2023-02-06 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20230207_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategories',
            old_name='catagories_id',
            new_name='categories_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 16, 41, 49, 882625, tzinfo=utc)),
        ),
    ]
