# Generated by Django 4.1.4 on 2023-02-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_post_expiration_alter_user_reputation_rating'),
        ('api', '0054_auto_20230207_0141'),
    ]

    operations = [
    ]
